============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: ~\exercism\python\error-handling, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 5 items

error_handling_test.py .....                                             [100%]

========================== 5 passed in 0.02 seconds ===========================

> python -m pytest error_handling_test.py

============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-3.10.1, py-1.6.0, pluggy-0.13.0
rootdir: ~\exercism\python\error-handling, inifile:
plugins: arraydiff-0.2, doctestplus-0.1.3, openfiles-0.3.0, remotedata-0.3.0
collected 5 items

error_handling_test.py .....                                             [100%]

========================== 5 passed in 0.19 seconds ===========================
